### ISSUE TITLE
RxJava1Converter can cause RxNetty to hang waiting for unsubscribe to request body Observable

### ISSUE THREAD

**Issue by rstoyanchev** [reactor/reactor#603] opened 2015-12-30 04:49 UTC
See the following [modified RxNetty sample](https://github.com/rstoyanchev/RxNetty/tree/hanging-issue). When using RxJava1Converter in the `performWork` method, the client hangs. Switching to RxReactiveStreams instead there is no hanging.

There is a `activeContentSubscriberExists` flag in `HttpServerToConnectionBridge` which is set to true when there is a subscriber for the request body and then to false when that unsubscribes. It works that way with RxReactiveStreams but not with RxJava1Converter. 

The hanging is because the HttpServerRequest.disposeContent tries to consume the content but thinks there is active consumer for the request body still and is placed on the `pendingContentSubs` queue (indefinitely).

**Comment by smaldini** [comment] 2015-12-30 09:44
I wonder if that is due to the difference in the spec between Rx and RS (and so reactor here). OnComplete and onError must never trigger cancel(), cancel is used to signal exception or stop consuming from onNext (or onSubscribe). 
Maybe RxJava/RxNetty expects that resources are "disposed" explicitely with unsubscribe. I wonder if @akarnokd you have an idea about that ?

**Comment by akarnokd** [comment] 2015-12-30 09:49
I couldn't find the source to RxJava1Converter, could you link it?

In RS, calling cancel when one is in onError and onComplete doesn't really matter because at that time, the Subscription and all associated resources should be considered cancelled. RxJava, however, somewhat expects it to call unsubscribe eventually otherwise things may leak.

Otherwise, I find it strange RxReactiveStreams works but plain RxJava doesn't since the former is just a wrapper on the latter.

**Comment by smaldini** [comment] 2015-12-30 11:49
https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/core/publisher/convert/RxJava1Converter.java

**Comment by smaldini** [comment] 2015-12-30 11:50
@akarnokd Context : the TCK enforces and test that subscribers don't call cancel in the onComplete or onError stack.

**Comment by akarnokd** [comment] 2015-12-30 12:03
Okay, just use `unsafeSubscribe` [here](https://github.com/reactor/reactor/blob/master/reactor-core/src/main/java/reactor/core/publisher/convert/RxJava1Converter.java#L76).

**Comment by rstoyanchev** [comment] 2015-12-30 13:55
> I wonder if that is due to the difference in the spec between Rx and RS (and so reactor here). OnComplete and onError must never trigger cancel().

That's what I was thinking but didn't get as far as checking.

> Okay, just use unsafeSubscribe here.

The challenge is if you're using any Reactive Streams components on top of RxNetty then you might be stuck. In the end this may end up being an issue for RxNetty to address. It does feel like if the request body content has been fully consumed it's a little fragile to then wait for a separate unsubscribe.

**Comment by smaldini** [comment] 2015-12-30 14:04
@rstoyanchev could you try with 2.5.0.BUILD-SNAPSHOT

**Comment by rstoyanchev** [comment] 2015-12-30 15:57
I tried 2.5.0, no change. 

Putting a break point in `SubscriberToRx` shows that the [unsubscribe method](https://github.com/reactor/reactor/blob/818350615ca3366d74867c87b78732d9dc61ba8b/reactor-core/src/main/java/reactor/core/publisher/convert/RxJava1Converter.java#L131) gets called both in 2.1 and in 2.5 but in both cases it's protected by the TERMINATED flag.

What is the effect that unsafeSubscribe is expected to have for this? Also I wonder what the impact is in a scenario where you have a mix. In other words not just a one time switch from RxJava to Reactive Straems in the pipeline but Rx then RS, then Rx again, RS, etc. This is not just a theoretical question actually considering that frameworks are expected to expose Reactive Streams in their APIs and remain agnostic to composition libraries.

**Comment by akarnokd** [comment] 2015-12-30 17:04
`subscribe` wraps the `rx.Subscriber` into a `SafeSubscriber` which calls `unsubscribe` on the terminal event. `unsafeSubscribe` doesn't wrap and its up to the `rx.Subscriber` what it will do.

What is the stacktrace at that point? (What I see is that the flag is flipped before the terminal event is emitted to rx and thus any unsubscribe call after it should not pass through.)

**Comment by rstoyanchev** [comment] 2015-12-30 18:30
This is stracktrace at the breakpoint in the unsubscribe method:
````
"rxnetty-nio-eventloop-1-3@996" daemon prio=5 tid=0xf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at reactor.core.publisher.convert.RxJava1Converter$SubscriberToRx.unsubscribe(RxJava1Converter.java:131)
	  at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
	  at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
	  at rx.Subscriber.unsubscribe(Subscriber.java:98)
	  at rx.subscriptions.SerialSubscription.unsubscribe(SerialSubscription.java:67)
	  at rx.internal.util.SubscriptionList.unsubscribeFromAll(SubscriptionList.java:124)
	  at rx.internal.util.SubscriptionList.unsubscribe(SubscriptionList.java:113)
	  at rx.Subscriber.unsubscribe(Subscriber.java:98)
	  at rx.subscriptions.SerialSubscription.set(SerialSubscription.java:93)
	  at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:175)
	  at rx.internal.operators.OperatorConcat$ConcatSubscriber.completeInner(OperatorConcat.java:162)
	  at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onCompleted(OperatorConcat.java:223)
	  at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$1.onCompleted(OperatorOnErrorResumeNextViaFunction.java:66)
	  at io.reactivex.netty.protocol.http.server.HttpConnectionHandler$2$1.onCompleted(HttpConnectionHandler.java:127)
	  at reactor.core.publisher.convert.RxJava1Converter$SubscriberToRx.onComplete(RxJava1Converter.java:172)
	  at reactor.core.subscriber.SubscriberBarrier.doComplete(SubscriberBarrier.java:128)
	  at reactor.core.subscriber.SubscriberBarrier.onComplete(SubscriberBarrier.java:121)
	  at reactor.rx.stream.StreamBatch$BatchAction.checkedComplete(StreamBatch.java:213)
	  at reactor.core.subscriber.SubscriberWithDemand.doComplete(SubscriberWithDemand.java:117)
	  at reactor.core.subscriber.SubscriberBarrier.onComplete(SubscriberBarrier.java:121)
	  at reactor.core.publisher.convert.RxJava1Converter$RxSubscriberToRS.onCompleted(RxJava1Converter.java:209)
	  at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:83)
	  at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge$ConnectionInputSubscriber.contentComplete(AbstractHttpConnectionBridge.java:474)
	  at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge.processNextItemInEventloop(AbstractHttpConnectionBridge.java:249)
	  at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge.access$1200(AbstractHttpConnectionBridge.java:53)
	  at io.reactivex.netty.protocol.http.internal.AbstractHttpConnectionBridge$ConnectionInputSubscriber.onNext(AbstractHttpConnectionBridge.java:397)
	  at io.reactivex.netty.channel.AbstractConnectionToChannelBridge$ReadProducer.sendOnNext(AbstractConnectionToChannelBridge.java:367)
	  at io.reactivex.netty.channel.AbstractConnectionToChannelBridge.newMessage(AbstractConnectionToChannelBridge.java:187)
	  at io.reactivex.netty.channel.BackpressureManagingHandler.channelRead(BackpressureManagingHandler.java:74)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:233)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	  at io.reactivex.netty.channel.BytesInspector.channelRead(BytesInspector.java:56)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	  at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
	  at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:153)
	  at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:157)
	  at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:946)
	  at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:125)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
	  at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
	  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	  at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	  at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
	  at java.lang.Thread.run(Thread.java:745)
````

**Comment by akarnokd** [comment] 2015-12-30 19:33
Thanks. It seems the SubscriberToRx.unsubscribe is called from the underlying rx.Subscriber in response of being evicted from a SerialSubscription of some operator. The eviction comes from a concat operator that switched to its next source and the old chain is unsubscribed downwards. This latter property of Rx concat is unfortunately an expected behavior by some tests.

The difference I see with the RxJavaReactiveStreams is that its converter uses strong serialization of request and cancel calls from the rx.Subscriber whereas your converter mostly passes it along. I'm assuming rx concatenates RS Publishers converted into Observables. I can't make out the RS Publisher from this stacktrace.

**Comment by smaldini** [comment] 2016-01-13 13:52
@rstoyanchev should that be considered fixed so far ?

**Comment by rstoyanchev** [comment] 2016-02-22 13:53
Last time I checked it's not fixed. It's still running with [the workaround](https://github.com/spring-projects/spring-reactive/blob/bd855be3ad150cf472a33b3efbcd97efe6c24776/src/main/java/org/springframework/http/server/reactive/RxNettyServerHttpRequest.java#L98).

**Comment by smaldini** [comment] 2016-02-22 14:08
unsafeSubscribe introduced issues we faced with @sdeleuze I can't remember the full context but we can do another pass after reactor-stream M1.

**Comment by rstoyanchev** [comment] 2016-02-22 14:22
I don't think it fixed it in any case if you see the comments above.

**Comment by smaldini** [comment] 2016-02-22 14:57
I meant I'm not sure if it did fix anything because once we did unsafeSubscribe it broke other tests from spring-reactive. So this fix didn't stay on master for a long time.

**Comment by rstoyanchev** [comment] 2016-02-22 15:47
Right, got it.

**Comment by sdeleuze** [comment] 2016-04-07 07:22
@smaldini What is the status of this issue? If still relevant may be nice to move it to `reactor-core` or `reactor-io` bugtracker?

**Comment by smaldini** [comment] 2016-04-07 09:58
If its not down to that unsafeSubscribe indeed, actually even if root cause might be that it should be pointed by a reactor-io issue.

**Comment by akarnokd** [comment] 2016-04-07 10:06
RxJava's `concat`/`concatMap` has been rewritten in 1.1.2. If it still doesn't work, a minimum reproducible example would be great.

**Comment by rstoyanchev** [comment] 2016-04-07 13:34
Checking..

**Comment by rstoyanchev** [comment] 2016-04-07 15:22
Looks like we have issues even trying to use the combination RxNetty 0.5.x + RxJava 1.1.2.

**Comment by akarnokd** [comment] 2016-04-07 15:47
There is a small issue with `concat`/`concatMap` in 1.1.2 when the concatenation involves a scalar `just()`. I'm working on it.

**Comment by akarnokd** [comment] 2016-04-07 16:13
Fix posted: https://github.com/ReactiveX/RxJava/pull/3840 in case you want to play with that before it gets into some release.

**Comment by smaldini** [comment] 2016-04-07 16:18
is there a snapshot build for Rx @akarnokd ?

**Comment by akarnokd** [comment] 2016-04-07 16:19
There is a snapshot for the main, but I don't think there is for PRs.

**Comment by akarnokd** [comment] 2016-04-07 16:40
If you are inclined, you could just apply `asObservable()` to any `just()` and `empty()` sources to hide their identities and disable optimizations that rely on them (i.e., concat/concatMap).

**Comment by rstoyanchev** [comment] 2016-04-07 16:45
For what it's worth the failures started with 1.1.1 https://github.com/ReactiveX/RxNetty/issues/491. That said I did publish the ConcatMapFix branch locally but the RxNetty failures don't go away. Our tests continue to hang too but I wouldn't take any guesses until RxNetty's own tests pass.

**Comment by akarnokd** [comment] 2016-04-07 16:50
The repo you linked at the top, is it the one still failing?

**Comment by rstoyanchev** [comment] 2016-04-07 17:02
Just clone RxNetty and run the tests in 0.5.x. The repo at the top changes one of the samples to demonstrate the original issue.

**Comment by akarnokd** [comment] 2016-04-07 17:05
RxNetty's own tests you mean? (The top repo doesn't compile for me on Java 8, full of ambiguous method calls.)

**Comment by rstoyanchev** [comment] 2016-04-07 17:07
Yes RxNetty's own tests. I did not run the one at the top today. I will check it.

**Comment by rstoyanchev** [comment] 2016-04-07 17:17
Check again. I've updated the hanging-issue branch referenced at the top.

**Comment by akarnokd** [comment] 2016-04-07 17:27
I've checked out RxNetty and for me, the testLoadBalancing fails: sometimes there is no 503, sometimes there is 2 and usually not in the expected order.

**Comment by akarnokd** [comment] 2016-04-07 17:44
I think that test relies on timing. It succeeds 1 out of 20 for me with 1.1.0 and almost never with 1.1.2.

**Comment by akarnokd** [comment] 2016-04-07 18:46
That test relies on a [random number generator](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-common/src/main/java/io/reactivex/netty/client/loadbalancer/AbstractP2CStrategy.java#L56) to pick hosts. RxNetty's own test didn't pass since it has proposed and [been merged](https://github.com/ReactiveX/RxNetty/commits/0.5.x/rxnetty-examples/src/main/java/io/reactivex/netty/examples/http/loadbalancing/HttpLoadBalancingClient.java)

**Comment by rstoyanchev** [comment] 2016-04-07 18:51
Perhaps comment under the RxNetty ticket I created. Is that the only one failing for you? I get about 3 failing tests (different ones) each time.

**Comment by akarnokd** [comment] 2016-04-07 18:58
In RxNetty master: yes. Rerun the whole set a couple of times but only the `testLoadBalancing` failed.

In your clone, the `testHelloWorld` times out, the rest run fine. I'll investigate that.

**Comment by akarnokd** [comment] 2016-04-07 19:16
In `testHelloWorld`, you forgot to write a response back so the client waits indefinitely. If update the code:

```java
package io.reactivex.netty.examples.http.helloworld;

import org.reactivestreams.Publisher;

import io.netty.buffer.ByteBuf;
import io.netty.handler.logging.LogLevel;
import io.reactivex.netty.examples.AbstractServerExample;
import io.reactivex.netty.protocol.http.server.*;
import io.reactivex.netty.spectator.http.HttpServerListener;
import reactor.core.converter.RxJava1ObservableConverter;
import reactor.core.publisher.Flux;
import rx.Observable;

/**
 * An HTTP "Hello World" server.
 *
 * This server sends a response with "Hello World" as the content for any request that it recieves.
 */
public final class HelloWorldServer extends AbstractServerExample {

    public static void main(final String[] args) {

        HttpServer<ByteBuf, ByteBuf> server;

        /*Starts a new HTTP server on an ephemeral port.*/
        server = HttpServer.newServer()
                .enableWireLogging(LogLevel.ERROR);
        server.subscribe(new HttpServerListener(""));
                           /*Starts the server with a request handler.*/
        server.start((req, resp) -> performWork(req, resp));

        /*Wait for shutdown if not called from the client (passed an arg)*/
        if (shouldWaitForShutdown(args)) {
            server.awaitShutdown();
        }

        /*If not waiting for shutdown, assign the ephemeral port used to a field so that it can be read and used by
        the caller, if any.*/
        setServerPort(server.getServerPort());
    }


    public static Observable<Void> performWork(HttpServerRequest<ByteBuf> request,
            HttpServerResponse<ByteBuf> response) {
        return RxJava1ObservableConverter.from(
                Flux.just(1).concatMap(i -> {
                    Publisher<ByteBuf> content = RxJava1ObservableConverter.from(request.getContent());
                    return Flux.from(content).buffer().after();
                }))
                .concatWith(response.writeString(Observable.just("Hello World!")));
    }

}
```

the test passes.

**Comment by rstoyanchev** [comment] 2016-04-07 20:16
No it wasn't an oversight. It's perfectly valid to consume the request body and do some work without writing to the response. The `Observable<Void>` indicates to RxNetty when the [RequestHandler](https://github.com/ReactiveX/RxNetty/blob/0.5.x/rxnetty-http/src/main/java/io/reactivex/netty/protocol/http/server/RequestHandler.java) is done. 

Also note that inserting a `concatWith` is our [current workaround](https://github.com/spring-projects/spring-reactive/blob/master/src/main/java/org/springframework/http/server/reactive/RxNettyServerHttpRequest.java#L92).

Try alternating between these two:
````java
public static Observable<Void> performWork(HttpServerRequest<ByteBuf> request,
        HttpServerResponse<ByteBuf> response) {

    // This works...
    return RxReactiveStreams.toObservable(
            Flux.just(1).concatMap(i -> {
                Publisher<ByteBuf> content = RxReactiveStreams.toPublisher(request.getContent());
                return Flux.from(content).buffer().after();
            }));

// This hangs...
//    return RxJava1ObservableConverter.from(
//            Flux.just(1).concatMap(i -> {
//                Publisher<ByteBuf> content = RxJava1ObservableConverter.from(request.getContent());
//                return Flux.from(content).buffer().after();
//            }));

}

**Comment by akarnokd** [comment] 2016-04-07 20:28
By works you mean doesn't hang but fails the test because it doesn't respond with the string, right?

**Comment by rstoyanchev** [comment] 2016-04-07 20:29
> In RxNetty master: yes.

That works for me too but we depend on 0.5.x (very different from 0.4.x) and that's the one I see multiple failures in.

**Comment by rstoyanchev** [comment] 2016-04-07 20:33
> By works you mean doesn't hang but fails the test because it doesn't respond with the string, right?

Yes. Sorry should have been more clear but what I'm doing is simply right-click and run HelloWorldClient.java which starts the server automatically.

**Comment by akarnokd** [comment] 2016-04-07 22:14
I've looked into it and it seems the reason RxReactiveStreams.toObservable works (even with RxJava1ObservableConverter.from) because when the concatMap swaps in the next source's subscriber, it triggers an unsubscription chain that calls `cancel()` on the chain no matter what. The converter, on the other hand, doesn't call `subscriber.cancel()` in `unsubscribe()` because the terminal flag has been set. 

If I change the converter to do not null out the `subscription` and then call `cancel()` on it in `unsubscribe()` always, there is no hang. If I instead call `subscription.cancel()` in `SubscriberToRx.onComplete` before or after the call `subscriber.onCompleted()` it hangs.

It seems the `subscriber.onCompleted()` does a chain of calls that enables the `subscription.cancel()` call to trigger cleanup of some RxJava/RxNetty operators that then no longer block after the swap.

I'll continue investigating the call chain tomorrow.

**Comment by akarnokd** [comment] 2016-04-08 10:54
I think I found the problem: it's in `io.reactivex.netty.protocol.http.server.HttpServerToConnectionBridge.userEventTriggered(ChannelHandlerContext, Object)`

If the `unsubscribe` is not called the first time, it fires the dequeued `HttpContentSubscriberEvent` event  which then goes through some handlers and get dropped. I believe the `ctx.fireUserEventTriggered(nextSub);` call is wrong here and it should instead do what the outer method does by calling `super.userEventTriggered(ctx, evt);`. If I change the method to this:

```java
    @Override
    public void userEventTriggered(final ChannelHandlerContext ctx, Object evt) throws Exception {
        if (evt instanceof HttpContentSubscriberEvent) {

            final HttpContentSubscriberEvent<?> subscriberEvent = (HttpContentSubscriberEvent<?>) evt;
            subscriberEvent.getSubscriber().add(Subscriptions.create(new Action0() {
                @Override
                public void call() {
                    HttpContentSubscriberEvent<?> nextSub = null;
                    synchronized (contentSubGuard) {
                        if (null != pendingContentSubs) {
                            nextSub = pendingContentSubs.poll();
                        }
                    }

                    activeContentSubscriberExists = null != nextSub;
                    if (null != nextSub) {
//                        ctx.fireUserEventTriggered(nextSub);
                        try {
                            manualTrigger(ctx, nextSub);
                        } catch (Exception ex) {
                            throw new RuntimeException(ex);
                        }
                    }
                }
            }));

            if (activeContentSubscriberExists) {
                synchronized (contentSubGuard) {
                    if (null == pendingContentSubs) {
                        pendingContentSubs = new ArrayDeque<>(); /*Guarded by contentSubGuard*/
                    }
                    pendingContentSubs.add(subscriberEvent);
                }
                return;
            }

            activeContentSubscriberExists = true;
        }

        // TODO: Handle trailers
        manualTrigger(ctx, evt);
    }

    void manualTrigger(final ChannelHandlerContext ctx, Object evt) throws Exception {
        super.userEventTriggered(ctx, evt);
    }
```

the test no longer hangs. I'm not sure about error handling of `super.userEventTriggered` inside the callback though.

**Comment by rstoyanchev** [comment] 2016-04-08 14:15
@akarnokd thanks for looking into this. 

I suppose calling cancel in terminal state would be against the Reactive Streams spec rules? In that sense `RxReactiveStreams` is not compliant but better bridges to expected RxJava1 semantics? Not sure if that's accurate or not but if so would it make sense to do the same in `RxJava1ObservableConverter` even if it's not RS spec compliant?

The other option is to treat this as an RxNetty issue and judging from the lack of activity in the RxNetty repository, not sure it's even worth reporting it. However I'm more concerned with similar subtle issues appearing in other circumstances.

**Comment by akarnokd** [comment] 2016-04-08 15:45
Calling cancel from the terminal state should be a no-op. That also means one should not rely on a child Subscriber to call cancel(). Unfortunately, RxJava 1 based libraries sometimes do expect it because SafeSubscriber calls unsubscribe.

In this particular case, this reliance on the call to unsubscribe hid another bug: a badly written trampolined event delivery.

The bug itself may materialize in some concurrent situations as well wether or not you are converting or not in the work handler; this is indeed an RxNetty bug and just by chance doesn't come up in the test with Rx's converter due to the synchronous nature of the processing.

I don't know what's the activity in RxNetty; I have merge rights there as well, but that doesn't mean anything. I certainly don't want to maintain RxNetty as well. I suggest submitting a PR with the fix and see if they do something about it.

**Comment by rstoyanchev** [comment] 2016-04-08 21:31
Sounds good, it seems to be inactive currently. Either way this can be closed.

**Closed** 2016-05-25 07:44 UTC
Labels: bug, current-sprint
